CREATE TABLE refers (
    Refer_ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID VARCHAR(10) NOT NULL,
    Refercode VARCHAR(20) NOT NULL,
    Used_by VARCHAR(100) NOT NULL,
    UsedOn DATETIME DEFAULT CURRENT_TIMESTAMP
);
